### ISSUE TITLE
Laravel Recipe

### ISSUE THREAD

**Issue by flyingluscas** [uselessdev/boost#4]
I think it would be nice if boost have a recipe for Laravel lovers, like me :D

**Comment by uselessdev** [comment]
It's a good ideia, you can help me with this? I don't know what is the best place for recipee, a folder named recipes maybe? What do you think?

**Comment by flyingluscas** [comment]
I think it's a good idea, I'm gonna start to build something like that, when it's ready I'll show you and we see if it's worth ok

**Comment by uselessdev** [comment]
ok. thanks
